export const SUCCESSFUL = "successful"
export const USER_LOCATIONS = "userLocations"
export const STATE_CHANGED= "state_changed"
export const USER_LOCATIONS_LOGO= "userLocationsLogo"
export const TILE_LAYER_ATTRIBUTION = "&copy; <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors"
export const TILE_LAYER_URL="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
export const NOTE_1 = "1-This application uses Firebase, turn on your VPN for better performance."
export const NOTE_2 = "2-For drag and drop markUp in Share Location Modal please click on mark up first and Then Drag And Drop MarkUp"